[package]
name = "phonoscule-tui"
description = "A TUI music player based on Phonoscule"
version = "0.1.0-dev"
publish = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
phonoscule = { path = "../phonoscule" }
crossterm = "0.29.0"
ratatui = "0.30.2"
ratatui-image = { version = "11.0.6", default-features = false, features = ["image-defaults", "crossterm"] }
image = "0.25.10"
