[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --baud 921600 --partition-table partitions.csv --erase-parts otadata --monitor --port /dev/ttyUSB0"

rustflags = "-C default-linker-libraries --cfg espidf_time64"

[profile.release]
opt-level = "s"
lto = true

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "branch:release/v5.1" }
ESP_IDF_SYS_ROOT_CRATE = { value = "phonoscule-micro" }
MCU = { value = "esp32c3" }
