[workspace]
members = ["phonoscule", "cli", "gui"]
resolver = "3"

[workspace.package]
authors = ["JoJo <jo@jo.zone>"]
version = "0.2.0"
edition = "2024"

[workspace.dependencies]
log = { version = "0.4.33", features = ["max_level_trace", "release_max_level_debug"] }
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
embedded-io-adapters = { version = "0.7.0", features = ["futures-03"] }
smol = "2.0"
simple_logger = "5.2"
