* Tasks
** TODO Write nice looking GUI app
I want a replacement for ~mpdevil~ not written in Python with GTK3.
I want an graphical music player that puts the albums and their covers in the centre, but with options for browsing by genre / artist as well.

This app is actually a bit of a priority, as ~mpdevil~ is not getting better for me.
The develper of upstream ~mpdevil~ is making changes I don't like, and now I'm having issues with theming in wayland.
The app is not properly following my system GTK theme and dark/light mode.
And porting the app to gtk4 seems like it's gonna be a bit of an effort if I attempt it myself.

So, why not kill two birds in one stone?

I don't really need to have opuscule or any of that stuff ready before writing the rest of this system.

Maybe use Rust and some nice UI framework.
Maybe add some nice visualizations as well?

Bevy seems like it could be a decent choice, if I intend to throw in some nice 3D effects & other visualizations.

https://bevyengine.org/examples/3d/parenting/
https://bevyengine.org/examples/3d/texture/
https://bevyengine.org/examples/3d/3d-shapes/
https://bevyengine.org/examples/2d/sprite/
https://bevyengine.org/examples/2d/text2d/
https://bevyengine.org/examples/shader/shader-material/
https://bevyengine.org/examples/ui/ui/
https://bevyengine.org/examples/ui/button/

https://zed.dev/blog/videogame

*** Coverflow-like thing
Maybe show the covers of each track in the current playlist / queue in a coverflow-like visualization.
Like a 3D wheel of covers spinning around the Y axis.
Above a frosted glass surface, showing blurred reflections of the covers.

Bevy has PBR, but not using ray tracing, so no reflections (not even screen space!).
But it could easily be faked.
Just duplicate the covers, transform them a bit, and throw on a filter to blur them.

** TODO Try compiling libopus for the esp32-c3
Maybe it works.
Maybe it's not even hard.
Might be worth it.
** NEXT Resampling
Should be able to resample e.g. a .wav at 44100Hz input to 48000Hz output.
Good resampling is based on FFT?
"The Quest For The Perfect Resampler" by Laurent de Soras, 2005
** TODO Wav
Pretty much the simplest format?
Would be good to start with, just to have something and being able to compare.
** TODO Flac (plain / simple / unwrapped)
I think most audiophiles don't actually use Wav in practice.
Flac yields smaller files, but still lossless.
I like flac.
Would be a nice format to have.
** TODO Ogg Flac
As a step towards ogg opus, ogg flac could be a good way of learning ogg.
** TODO Ogg Opus
The real target.
This is what we'll actually be playing in practice.
https://www.jefftk.com/p/bucket-brigade-singing
** INACTIVE Support QOA (Quite Ok Audio format) codec
https://phoboslab.org/log/2023/02/qoa-time-domain-audio-compression

* Inspo / related work / useful tools

https://github.com/Borewit/music-metadata

might be able to use nom for parsing. See this:
https://github.com/rust-bakery/nom/blob/main/doc/custom_input_types.md

https://sr.ht/~jacqueline/tangara/
