[package]
name = "phonoscule"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
# rev is latest as of its commit date 2026-07-05
opuscule = { git = "https://codeberg.org/jojo-laplace/opuscule", rev = "baeb2b21eae752c898ba9638a6c91b1b3f71ee31" }
ogg = "0.9.2"
utf8-decode = "2.0"
embedded-io       = { workspace = true }
embedded-io-async = { workspace = true }
log               = { workspace = true }

[dev-dependencies]
embedded-io-adapters = { workspace = true }
smol                 = { workspace = true }
simple_logger        = { workspace = true }
criterion            = "0.8"

[[bench]]
name = "parse"
harness = false
