[package]
name = "phonoscule"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
utf8-decode = "2.0"
embedded-io       = { workspace = true }
embedded-io-async = { workspace = true }
log               = { workspace = true }

[dev-dependencies]
embedded-io-adapters = { workspace = true }
tokio                = { workspace = true, features = ["io-util", "fs"] }
simple_logger        = { workspace = true }
