[package]
name = "phonoscule-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.26", features = ["event-stream"] }
futures = "0.3"
pulse-simple = "1.0.1"
ringbuf = "0.3"
phonoscule = { path = "../" }
embedded-io   = { workspace = true, features = ["tokio"] }
tokio         = { workspace = true, features = ["sync", "time", "io-util", "fs"] }
simple_logger = { workspace = true, features = ["stderr"] }
log           = { workspace = true }