[package]
name = "phonoscule-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.26", features = ["event-stream"] }
futures = "0.3"
pulse-simple = "1.0.1"
ringbuf = "0.3"
tokio = { version = "1.26", features = ["rt", "sync", "time", "macros"] }
phonoscule = { path = "../" }
simple_logger = { workspace = true, features = ["stderr"] }
log           = { workspace = true }